<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DELL" name="com.w2a.archBatch2.TestCases.ValidateFacebookLogin" tests="2" failures="0" timestamp="18 Mar 2018 10:06:42 GMT" time="95.007" errors="2">
  <testcase name="tc_02" time="53.803" classname="com.w2a.archBatch2.TestCases.ValidateFacebookLogin">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.w2a.archBatch2.PageObjects.BasePage.waitForPageLoad(BasePage.java:35)
	at com.w2a.archBatch2.PageObjects.BasePage.openPage(BasePage.java:27)
	at com.w2a.archBatch2.PageObjects.FacebookLandingPage.doLoginWithValidCredentials(FacebookLandingPage.java:46)
	at com.w2a.archBatch2.TestCases.ValidateFacebookLogin.tc_02(ValidateFacebookLogin.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- tc_02 -->
  <testcase name="validateFBLoginWIthValidCredentials" time="41.204" classname="com.w2a.archBatch2.TestCases.ValidateFacebookLogin">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.w2a.archBatch2.PageObjects.BasePage.waitForPageLoad(BasePage.java:35)
	at com.w2a.archBatch2.PageObjects.BasePage.openPage(BasePage.java:27)
	at com.w2a.archBatch2.PageObjects.FacebookLandingPage.doLoginWithValidCredentials(FacebookLandingPage.java:46)
	at com.w2a.archBatch2.TestCases.ValidateFacebookLogin.validateFBLoginWIthValidCredentials(ValidateFacebookLogin.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- validateFBLoginWIthValidCredentials -->
</testsuite> <!-- com.w2a.archBatch2.TestCases.ValidateFacebookLogin -->
